[package]
name = "herman"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Brittain <ben@brittain.org>"]


[dependencies]
tokio = { version = "1", features = ["full"] }
prost = "0.10"
prost-types = "0.10"
reqwest = "0.11"
anyhow = "1.0.66"

[build-dependencies]
prost-build = "0.10"
